# Generated by Django 2.2 on 2020-11-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('options', models.CharField(choices=[('sur', 'Survey'), ('dis', 'Discussion'), ('dia', 'Diary')], default='sur', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_data', models.DateField(verbose_name='Launch Data')),
                ('status', models.CharField(choices=[('liv', 'Live'), ('pen', 'Pending'), ('arc', 'Archived')], default='pen', max_length=3)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_software.TaskObjects')),
            ],
        ),
    ]
