# Generated by Django 2.2 on 2020-11-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Launch_data', models.DateField()),
                ('Status', models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('archived', 'Archived')], default='pending', max_length=10)),
            ],
            options={
                'ordering': ['-Launch_data'],
            },
        ),
        migrations.CreateModel(
            name='TaskObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
                ('Order', models.IntegerField(blank=True, choices=[('1', 'postion 1'), ('2', 'postion 2'), ('3', 'postion 3'), ('4', 'postion 4')], default=None, null=True)),
                ('Type', models.CharField(choices=[('survey', 'Survey'), ('discussion', 'Discussion'), ('diary', 'Diary')], default='survey', max_length=10)),
                ('Tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='research_software.TileObject')),
            ],
        ),
    ]
