# Generated by Django 2.2 on 2020-11-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TileObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Launch_data', models.DateField(verbose_name='Launch Data')),
                ('Status', models.CharField(choices=[('live', 'Live'), ('pending', 'Pending'), ('archived', 'Archived')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TaskObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Description', models.TextField()),
                ('Order', models.IntegerField(unique=True)),
                ('Type', models.CharField(choices=[('sur', 'Survey'), ('dis', 'Discussion'), ('dia', 'Diary')], default='sur', max_length=10)),
                ('Tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_software.TileObject')),
            ],
        ),
    ]
