# Generated by Django 2.2 on 2020-11-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskObjects',
            new_name='TaskObject',
        ),
    ]
