# Generated by Django 2.2 on 2020-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tileobject',
            name='Launch_data',
            field=models.DateField(),
        ),
    ]
