# Generated by Django 2.2 on 2020-11-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0002_auto_20201110_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobject',
            name='Type',
            field=models.CharField(choices=[('survey', 'Survey'), ('discussion', 'Discussion'), ('diary', 'Diary')], default='survey', max_length=10),
        ),
    ]
