# Generated by Django 2.2 on 2020-11-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0002_auto_20201109_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskobject',
            old_name='options',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='tileobject',
            old_name='launch_data',
            new_name='Launch_data',
        ),
        migrations.RenameField(
            model_name='tileobject',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='tileobject',
            old_name='tasks',
            new_name='Tasks',
        ),
        migrations.AddField(
            model_name='taskobject',
            name='Order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
