# Generated by Django 2.2 on 2020-11-10 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0002_auto_20201110_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobject',
            name='Tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='research_software.TileObject'),
        ),
    ]
