# Generated by Django 2.2 on 2020-11-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0003_auto_20201109_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobject',
            name='Title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tileobject',
            name='Tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_software.TaskObject', to_field='Title'),
        ),
    ]
