# Generated by Django 2.2 on 2020-11-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0003_auto_20201110_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobject',
            name='Tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research_software.TileObject'),
        ),
    ]
