# Generated by Django 2.2 on 2020-11-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0003_auto_20201110_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tileobject',
            options={'ordering': ['-Launch_data']},
        ),
        migrations.AlterField(
            model_name='taskobject',
            name='Tile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='research_software.TileObject'),
        ),
    ]
