# Generated by Django 2.2 on 2020-11-09 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0005_auto_20201109_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskobject',
            name='Tasks',
        ),
        migrations.AddField(
            model_name='taskobject',
            name='Tile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research_software.TileObject'),
            preserve_default=False,
        ),
    ]
