# Generated by Django 2.2 on 2020-11-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0005_auto_20201110_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskobject',
            name='Order',
            field=models.IntegerField(blank=True, choices=[('1', 'postion 1'), ('2', 'postion 2'), ('3', 'postion 3'), ('4', 'postion 4')], default=None),
        ),
    ]
