# Generated by Django 2.2 on 2020-11-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_software', '0005_auto_20201110_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tileobject',
            options={'ordering': ['-Launch_date']},
        ),
        migrations.RenameField(
            model_name='tileobject',
            old_name='Launch_data',
            new_name='Launch_date',
        ),
    ]
